// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type AiExtractionsStatus string

const (
	AiExtractionsStatusSuccess AiExtractionsStatus = "success"
	AiExtractionsStatusPartial AiExtractionsStatus = "partial"
	AiExtractionsStatusFailed  AiExtractionsStatus = "failed"
)

func (e *AiExtractionsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AiExtractionsStatus(s)
	case string:
		*e = AiExtractionsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AiExtractionsStatus: %T", src)
	}
	return nil
}

type NullAiExtractionsStatus struct {
	AiExtractionsStatus AiExtractionsStatus `json:"ai_extractions_status"`
	Valid               bool                `json:"valid"` // Valid is true if AiExtractionsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAiExtractionsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AiExtractionsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AiExtractionsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAiExtractionsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AiExtractionsStatus), nil
}

type ScheduleRemindersChannel string

const (
	ScheduleRemindersChannelPush  ScheduleRemindersChannel = "push"
	ScheduleRemindersChannelEmail ScheduleRemindersChannel = "email"
	ScheduleRemindersChannelNone  ScheduleRemindersChannel = "none"
)

func (e *ScheduleRemindersChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScheduleRemindersChannel(s)
	case string:
		*e = ScheduleRemindersChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for ScheduleRemindersChannel: %T", src)
	}
	return nil
}

type NullScheduleRemindersChannel struct {
	ScheduleRemindersChannel ScheduleRemindersChannel `json:"schedule_reminders_channel"`
	Valid                    bool                     `json:"valid"` // Valid is true if ScheduleRemindersChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScheduleRemindersChannel) Scan(value interface{}) error {
	if value == nil {
		ns.ScheduleRemindersChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScheduleRemindersChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScheduleRemindersChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScheduleRemindersChannel), nil
}

type SchedulesSource string

const (
	SchedulesSourceManual SchedulesSource = "manual"
	SchedulesSourceAi     SchedulesSource = "ai"
)

func (e *SchedulesSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SchedulesSource(s)
	case string:
		*e = SchedulesSource(s)
	default:
		return fmt.Errorf("unsupported scan type for SchedulesSource: %T", src)
	}
	return nil
}

type NullSchedulesSource struct {
	SchedulesSource SchedulesSource `json:"schedules_source"`
	Valid           bool            `json:"valid"` // Valid is true if SchedulesSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSchedulesSource) Scan(value interface{}) error {
	if value == nil {
		ns.SchedulesSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SchedulesSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSchedulesSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SchedulesSource), nil
}

type SchedulesStatus string

const (
	SchedulesStatusConfirmed SchedulesStatus = "confirmed"
	SchedulesStatusTentative SchedulesStatus = "tentative"
	SchedulesStatusCancelled SchedulesStatus = "cancelled"
)

func (e *SchedulesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SchedulesStatus(s)
	case string:
		*e = SchedulesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SchedulesStatus: %T", src)
	}
	return nil
}

type NullSchedulesStatus struct {
	SchedulesStatus SchedulesStatus `json:"schedules_status"`
	Valid           bool            `json:"valid"` // Valid is true if SchedulesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSchedulesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SchedulesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SchedulesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSchedulesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SchedulesStatus), nil
}

type AiExtraction struct {
	ID         []byte              `json:"id"`
	UserID     []byte              `json:"user_id"`
	Model      string              `json:"model"`
	InputChars int32               `json:"input_chars"`
	RawText    sql.NullString      `json:"raw_text"`
	ResultJson json.RawMessage     `json:"result_json"`
	Status     AiExtractionsStatus `json:"status"`
	LatencyMs  sql.NullInt32       `json:"latency_ms"`
	CreatedAt  time.Time           `json:"created_at"`
}

type Schedule struct {
	ID           []byte          `json:"id"`
	UserID       []byte          `json:"user_id"`
	Title        string          `json:"title"`
	Description  sql.NullString  `json:"description"`
	Location     sql.NullString  `json:"location"`
	StartAt      time.Time       `json:"start_at"`
	EndAt        sql.NullTime    `json:"end_at"`
	AllDay       bool            `json:"all_day"`
	Status       SchedulesStatus `json:"status"`
	Source       SchedulesSource `json:"source"`
	ExtractionID sql.NullString  `json:"extraction_id"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type ScheduleReminder struct {
	ID            []byte                   `json:"id"`
	ScheduleID    []byte                   `json:"schedule_id"`
	MinutesBefore int32                    `json:"minutes_before"`
	Channel       ScheduleRemindersChannel `json:"channel"`
	CreatedAt     time.Time                `json:"created_at"`
}
