// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	AddReminder(ctx context.Context, arg AddReminderParams) error
	CreateExtraction(ctx context.Context, arg CreateExtractionParams) error
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) error
	DeleteReminder(ctx context.Context, arg DeleteReminderParams) (int64, error)
	DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) (int64, error)
	DeleteSchedulesByIDs(ctx context.Context, arg DeleteSchedulesByIDsParams) (int64, error)
	GetSchedule(ctx context.Context, arg GetScheduleParams) (*Schedule, error)
	ListReminders(ctx context.Context, scheduleID []byte) ([]*ScheduleReminder, error)
	ListSchedules(ctx context.Context, arg ListSchedulesParams) ([]*Schedule, error)
	UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) error
}

var _ Querier = (*Queries)(nil)
