// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
	"strings"
	"time"
)

const addReminder = `-- name: AddReminder :exec
INSERT INTO schedule_reminders (id, schedule_id, minutes_before, channel)
VALUES (?, ?, ?, ?)
`

type AddReminderParams struct {
	ID            []byte                   `json:"id"`
	ScheduleID    []byte                   `json:"schedule_id"`
	MinutesBefore int32                    `json:"minutes_before"`
	Channel       ScheduleRemindersChannel `json:"channel"`
}

func (q *Queries) AddReminder(ctx context.Context, arg AddReminderParams) error {
	_, err := q.db.ExecContext(ctx, addReminder,
		arg.ID,
		arg.ScheduleID,
		arg.MinutesBefore,
		arg.Channel,
	)
	return err
}

const createExtraction = `-- name: CreateExtraction :exec
INSERT INTO ai_extractions (
  id, user_id, model, input_chars, raw_text, result_json, status, latency_ms
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateExtractionParams struct {
	ID         []byte              `json:"id"`
	UserID     []byte              `json:"user_id"`
	Model      string              `json:"model"`
	InputChars int32               `json:"input_chars"`
	RawText    sql.NullString      `json:"raw_text"`
	ResultJson json.RawMessage     `json:"result_json"`
	Status     AiExtractionsStatus `json:"status"`
	LatencyMs  sql.NullInt32       `json:"latency_ms"`
}

func (q *Queries) CreateExtraction(ctx context.Context, arg CreateExtractionParams) error {
	_, err := q.db.ExecContext(ctx, createExtraction,
		arg.ID,
		arg.UserID,
		arg.Model,
		arg.InputChars,
		arg.RawText,
		arg.ResultJson,
		arg.Status,
		arg.LatencyMs,
	)
	return err
}

const createSchedule = `-- name: CreateSchedule :exec
INSERT INTO schedules (
  id, user_id, title, description, location, start_at, end_at, all_day, status, source, extraction_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateScheduleParams struct {
	ID           []byte          `json:"id"`
	UserID       []byte          `json:"user_id"`
	Title        string          `json:"title"`
	Description  sql.NullString  `json:"description"`
	Location     sql.NullString  `json:"location"`
	StartAt      time.Time       `json:"start_at"`
	EndAt        sql.NullTime    `json:"end_at"`
	AllDay       bool            `json:"all_day"`
	Status       SchedulesStatus `json:"status"`
	Source       SchedulesSource `json:"source"`
	ExtractionID sql.NullString  `json:"extraction_id"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) error {
	_, err := q.db.ExecContext(ctx, createSchedule,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartAt,
		arg.EndAt,
		arg.AllDay,
		arg.Status,
		arg.Source,
		arg.ExtractionID,
	)
	return err
}

const deleteReminder = `-- name: DeleteReminder :execrows
DELETE FROM schedule_reminders
WHERE id = ? AND schedule_id = ?
`

type DeleteReminderParams struct {
	ID         []byte `json:"id"`
	ScheduleID []byte `json:"schedule_id"`
}

func (q *Queries) DeleteReminder(ctx context.Context, arg DeleteReminderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteReminder, arg.ID, arg.ScheduleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSchedule = `-- name: DeleteSchedule :execrows
DELETE FROM schedules
WHERE id = ? AND user_id = ?
`

type DeleteScheduleParams struct {
	ID     []byte `json:"id"`
	UserID []byte `json:"user_id"`
}

func (q *Queries) DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSchedule, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSchedulesByIDs = `-- name: DeleteSchedulesByIDs :execrows
DELETE FROM schedules
WHERE user_id = ? AND id IN (/*SLICE:ids*/?)
`

type DeleteSchedulesByIDsParams struct {
	UserID []byte   `json:"user_id"`
	Ids    [][]byte `json:"ids"`
}

func (q *Queries) DeleteSchedulesByIDs(ctx context.Context, arg DeleteSchedulesByIDsParams) (int64, error) {
	query := deleteSchedulesByIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listScheduleIDsByIDs = `-- name: ListScheduleIDsByIDs :many
SELECT id FROM schedules
WHERE user_id = ? AND id IN (/*SLICE:ids*/?)
`

type ListScheduleIDsByIDsParams struct {
	UserID []byte   `json:"user_id"`
	Ids    [][]byte `json:"ids"`
}

func (q *Queries) ListScheduleIDsByIDs(ctx context.Context, arg ListScheduleIDsByIDsParams) ([][]byte, error) {
	query := listScheduleIDsByIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var id []byte
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, user_id, title, description, location, start_at, end_at, all_day, status, source, extraction_id, created_at, updated_at FROM schedules
WHERE id = ? AND user_id = ?
`

type GetScheduleParams struct {
	ID     []byte `json:"id"`
	UserID []byte `json:"user_id"`
}

func (q *Queries) GetSchedule(ctx context.Context, arg GetScheduleParams) (*Schedule, error) {
	row := q.db.QueryRowContext(ctx, getSchedule, arg.ID, arg.UserID)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartAt,
		&i.EndAt,
		&i.AllDay,
		&i.Status,
		&i.Source,
		&i.ExtractionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listReminders = `-- name: ListReminders :many
SELECT id, schedule_id, minutes_before, channel, created_at FROM schedule_reminders
WHERE schedule_id = ?
ORDER BY minutes_before ASC
`

func (q *Queries) ListReminders(ctx context.Context, scheduleID []byte) ([]*ScheduleReminder, error) {
	rows, err := q.db.QueryContext(ctx, listReminders, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ScheduleReminder{}
	for rows.Next() {
		var i ScheduleReminder
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.MinutesBefore,
			&i.Channel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, user_id, title, description, location, start_at, end_at, all_day, status, source, extraction_id, created_at, updated_at FROM schedules
WHERE user_id = ?
  AND start_at >= ?
  AND start_at < ?
  AND (? IS NULL OR status = ?)
ORDER BY start_at ASC
`

type ListSchedulesParams struct {
	UserID    []byte              `json:"user_id"`
	StartAt   time.Time           `json:"start_at"`
	StartAt_2 time.Time           `json:"start_at_2"`
	Status    NullSchedulesStatus `json:"status"`
}

func (q *Queries) ListSchedules(ctx context.Context, arg ListSchedulesParams) ([]*Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedules,
		arg.UserID,
		arg.StartAt,
		arg.StartAt_2,
		arg.Status,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartAt,
			&i.EndAt,
			&i.AllDay,
			&i.Status,
			&i.Source,
			&i.ExtractionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedule = `-- name: UpdateSchedule :exec
UPDATE schedules
SET title       = ?,
    description = ?,
    location    = ?,
    start_at    = ?,
    end_at      = ?,
    all_day     = ?,
    status      = ?
WHERE id = ? AND user_id = ?
`

type UpdateScheduleParams struct {
	Title       string          `json:"title"`
	Description sql.NullString  `json:"description"`
	Location    sql.NullString  `json:"location"`
	StartAt     time.Time       `json:"start_at"`
	EndAt       sql.NullTime    `json:"end_at"`
	AllDay      bool            `json:"all_day"`
	Status      SchedulesStatus `json:"status"`
	ID          []byte          `json:"id"`
	UserID      []byte          `json:"user_id"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) error {
	_, err := q.db.ExecContext(ctx, updateSchedule,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartAt,
		arg.EndAt,
		arg.AllDay,
		arg.Status,
		arg.ID,
		arg.UserID,
	)
	return err
}
